[package]
name = "mips"
version = "0.1.0"
authors = ["Marc Cataford <c.marcandre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
maplit = "1.0.2"
